// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhlxhnhbfgmrwfirihxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxobHhobmhiZmdtcndmaXJpaHhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzU1MDMsImV4cCI6MjA2MDkxMTUwM30.K7O7jHgJLfTooO2tGP4DeTqsEcIONsiHWLVPn9su1wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);